# Generated by Django 6.0.5 on 2026-05-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_navigationsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationSettings',
        ),
    ]
