# Generated by Django 6.0.5 on 2026-06-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_hashi_image_homepage_hashi_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='aboutus_text1',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
