# Generated by Django 6.0.5 on 2026-06-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_aboutus_text1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='aboutus_text1',
            new_name='About_Us_Text_1',
        ),
    ]
