# Generated by Django 6.0.5 on 2026-06-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_aboutus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='About_Us_Text_2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
