# Generated by Django 6.0.5 on 2026-06-08 10:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_image_4_homepage_image_5_homepage_image_6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='aboutus_gallery',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}),
        ),
    ]
