# Generated by Django 6.0.5 on 2026-06-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_privacypolicypage_privacypolicy'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivacyPolicy',
            new_name='PrivacyPolicyPage',
        ),
    ]
