# Generated by Django 6.0.5 on 2026-06-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_privacypolicy_privacypolicypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicypage',
            name='Title',
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='last_update',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='text_1',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
