# Generated by Django 6.0.5 on 2026-06-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_privacypolicypage_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicypage',
            name='text_1',
            field=models.TextField(blank=True),
        ),
    ]
