# Generated by Django 6.0.5 on 2026-06-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_privacypolicypage_text_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicypage',
            name='subtext_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='subtext_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='subtext_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='subtext_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='subtitle_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='subtitle_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='subtitle_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='subtitle_4',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
