# Generated by Django 6.0.5 on 2026-06-22 15:06

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_privacypolicypage_subtext_1_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='django_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='django_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='docker_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='docker_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='flutter_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='flutter_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='graphql_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='graphql_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hashi_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hashi_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='mongo_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='mongo_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='postgre_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='postgre_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='react_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='react_text',
        ),
        migrations.CreateModel(
            name='TechnologyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
