# Generated by Django 6.0.5 on 2026-05-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_footersettings_finaciamento_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='adress',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Email'),
        ),
    ]
