# Generated by Django 6.0.5 on 2026-05-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_footersettings_adress_footersettings_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footersettings',
            old_name='adress',
            new_name='address',
        ),
    ]
