# Generated by Django 6.0.5 on 2026-06-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_socialslogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialslogo',
            old_name='page',
            new_name='footer',
        ),
    ]
