# Generated by Django 6.0.5 on 2026-06-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_page_socialslogo_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='facebook_icon',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='instagram_icon',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='linkedin_icon',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='whatsapp_icon',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='whatsapp_url',
        ),
    ]
